version: "3.9"
services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      
      # SERVER SETTINGS
      DIFFICULTY: "normal"
      MOTD: "§l§cWelcome Bastard!§r"
      ICON: "/extra/server_icon.jpg"
      MAX_PLAYERS: 10
      SERVER_NAME: "Fellowship of Bastards Modded Minecraft Server"
      WHITELIST_FILE: "/extra/whitelist.json"
      OPS_FILE: "/extra/ops.json"
      RCON_CMDS_STARTUP:  |-
        gamerule doFireTick false

      # FORGE SETUP
      TYPE: FORGE
      VERSION: 1.19.2
      FORGE_VERSION: 43.1.7

      # DATAPACKS
      VANILLATWEAKS_SHARECODE: P2nUIm

    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./extra:/extra
  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "2h"
      # instead of network_mode below, could declare RCON_HOST
      # RCON_HOST: mc
    volumes:
      # mount the same volume used by server, but read-only
      - mc:/data:ro
      # use a host attached directory so that it in turn can be backed up
      # to external/cloud storage
      - ./mc-backups:/backups
    # share network namespace with server to simplify rcon access
    network_mode: "service:mc"

volumes:
  mc: {}